export const mockData = [
  {
    id: "2bf6f948-5ae5-42de-b537-32f0620a2f3f",
    name: "Puff Jillions",
    age: 1,
    gender: "Male",
    description:
      "amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices",
    category: null,
    image: "http://dummyimage.com/209x436.png/5fa2dd/ffffff",
    prizemoney: "$25.69",
    status: 3,
  },
  {
    id: "16e89590-fcc9-4982-8e8e-b8d2f7ef5304",
    name: "Rikki Ruddiman",
    age: 57,
    gender: "Male",
    description:
      "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget",
    category: null,
    image: "http://dummyimage.com/679x473.png/dddddd/000000",
    prizemoney: "$70.59",
    status: null,
  },
  {
    id: "1eacb0b3-655d-46bd-bf66-0d1811e8be50",
    name: "Gwyn Grigoire",
    age: 55,
    gender: "Female",
    description:
      "nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit",
    category: null,
    image: "http://dummyimage.com/603x376.png/dddddd/000000",
    prizemoney: "$76.17",
    status: 2,
  },
  {
    id: "0f8dc005-0bba-4dec-a2e5-1af01bafd3eb",
    name: "Hadrian Dowse",
    age: 87,
    gender: null,
    description:
      "vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus",
    category: null,
    image: "http://dummyimage.com/722x413.png/ff4444/ffffff",
    prizemoney: null,
    status: 3,
  },
  {
    id: "9fdbf552-3c0a-49f0-9830-f00b8151493c",
    name: "Trev Jerdon",
    age: 9,
    gender: "Male",
    description:
      "posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti",
    category: null,
    image: "http://dummyimage.com/234x254.png/5fa2dd/ffffff",
    prizemoney: "$11.67",
    status: 1,
  },
  {
    id: "e5f4834d-21ec-4556-a201-1be2302cc5d8",
    name: "Homere Dancey",
    age: 57,
    gender: "Male",
    description:
      "eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec",
    category: null,
    image: "http://dummyimage.com/335x389.png/5fa2dd/ffffff",
    prizemoney: null,
    status: 1,
  },
  {
    id: "843e096b-e8a0-44ac-bd08-2cb406c960b2",
    name: "Freda Hoodlass",
    age: 14,
    gender: "Female",
    description:
      "iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo",
    category: null,
    image: "http://dummyimage.com/485x663.png/5fa2dd/ffffff",
    prizemoney: "$96.98",
    status: null,
  },
  {
    id: "aca927ae-33ee-40c0-b540-841765ee8fdb",
    name: "Orion Trevascus",
    age: 68,
    gender: "Male",
    description:
      "quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",
    category: null,
    image: "http://dummyimage.com/582x452.png/dddddd/000000",
    prizemoney: "$14.07",
    status: null,
  },
  {
    id: "a9a461ce-16a2-4419-85b6-f6ad2f2c6d6c",
    name: "Olivero Jakoviljevic",
    age: 81,
    gender: "Male",
    description:
      "suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus",
    category: null,
    image: "http://dummyimage.com/468x296.png/cc0000/ffffff",
    prizemoney: "$52.97",
    status: 1,
  },
  {
    id: "0d54087c-21a4-454e-b6ff-a97540feb5d9",
    name: "Gasparo Benettini",
    age: 59,
    gender: null,
    description:
      "ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui",
    category: null,
    image: "http://dummyimage.com/772x291.png/5fa2dd/ffffff",
    prizemoney: "$39.76",
    status: 3,
  },
  {
    id: "3540f23c-ace9-4a13-879e-63de02a84258",
    name: "Abbott McPartlin",
    age: 32,
    gender: "Male",
    description:
      "nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem",
    category: null,
    image: "http://dummyimage.com/539x687.png/ff4444/ffffff",
    prizemoney: "$52.12",
    status: 1,
  },
  {
    id: "1e0fb8db-9844-487a-af3e-4c82ff574fb6",
    name: "Pacorro Le Fevre",
    age: 69,
    gender: "Male",
    description:
      "nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel",
    category: null,
    image: "http://dummyimage.com/581x227.png/5fa2dd/ffffff",
    prizemoney: "$43.90",
    status: 1,
  },
  {
    id: "f095ceb2-7493-484a-9ccf-17e0b7cc8ab2",
    name: "Lothario Lamburne",
    age: 14,
    gender: "Male",
    description:
      "placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula",
    category: null,
    image: "http://dummyimage.com/582x478.png/dddddd/000000",
    prizemoney: null,
    status: 1,
  },
  {
    id: "c921bffe-313b-47b0-8457-ca7b82b01432",
    name: "Ara Causby",
    age: 40,
    gender: "Female",
    description:
      "vestibulum sit amet cursus id turpis integer aliquet massa id lobortis",
    category: null,
    image: "http://dummyimage.com/663x381.png/cc0000/ffffff",
    prizemoney: "$32.08",
    status: 3,
  },
  {
    id: "d6c7b474-f3db-4e72-bfe7-69d07a24a7b3",
    name: "Lorilee De Haven",
    age: 39,
    gender: "Female",
    description:
      "maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo",
    category: null,
    image: "http://dummyimage.com/647x768.png/5fa2dd/ffffff",
    prizemoney: "$87.55",
    status: null,
  },
  {
    id: "80524303-d47a-4bcf-bc24-e9619f7a61be",
    name: "Alley McElory",
    age: 56,
    gender: "Male",
    description:
      "bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus",
    category: null,
    image: "http://dummyimage.com/790x672.png/ff4444/ffffff",
    prizemoney: "$45.69",
    status: 2,
  },
  {
    id: "a75b6f20-3ece-44a6-9af4-39d5d1ec1b10",
    name: "Flora Spurden",
    age: 59,
    gender: "Female",
    description:
      "leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor",
    category: null,
    image: "http://dummyimage.com/789x344.png/ff4444/ffffff",
    prizemoney: "$42.59",
    status: 1,
  },
  {
    id: "0f0b6bc9-311e-4668-819a-5096bb43c4c4",
    name: "Verne MacCheyne",
    age: 84,
    gender: null,
    description:
      "aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut",
    category: null,
    image: "http://dummyimage.com/419x728.png/cc0000/ffffff",
    prizemoney: null,
    status: 1,
  },
  {
    id: "f82b5dcc-6369-4c41-a52b-b2bb916a288b",
    name: "Thatch Silbert",
    age: 12,
    gender: "Male",
    description:
      "potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue",
    category: null,
    image: "http://dummyimage.com/779x327.png/5fa2dd/ffffff",
    prizemoney: null,
    status: null,
  },
  {
    id: "edf9d917-3d2a-437e-ad43-bc184409cc9a",
    name: "Olag Howley",
    age: 77,
    gender: "Male",
    description:
      "mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec",
    category: null,
    image: "http://dummyimage.com/276x778.png/5fa2dd/ffffff",
    prizemoney: "$53.26",
    status: null,
  },
  {
    id: "afc7cd84-09fe-4199-9eae-5f11ab68dd9f",
    name: "Beniamino Kennifeck",
    age: 16,
    gender: "Male",
    description:
      "aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea",
    category: null,
    image: "http://dummyimage.com/741x383.png/5fa2dd/ffffff",
    prizemoney: "$47.82",
    status: 1,
  },
  {
    id: "005690ce-6b54-48bf-b020-edc8b8c2ad09",
    name: "Nicoli Little",
    age: 62,
    gender: "Female",
    description:
      "aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis",
    category: null,
    image: "http://dummyimage.com/382x238.png/5fa2dd/ffffff",
    prizemoney: "$49.00",
    status: 3,
  },
  {
    id: "6d074704-a6e7-4f8b-87e6-c6a55d8916f1",
    name: "Mitchael Blackwell",
    age: 19,
    gender: "Male",
    description:
      "sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi",
    category: null,
    image: "http://dummyimage.com/441x568.png/cc0000/ffffff",
    prizemoney: "$1.25",
    status: 2,
  },
];
